FROM pytorch/pytorch:latest

# Install astro Python packages
RUN conda install torchvision ignite -c pytorch -y
RUN conda install astropy -y
RUN pip install spectral-cube

# Add the torch-geometric packages
RUN conda install jupyterlab

RUN pip install --upgrade torch-scatter
RUN pip install --upgrade torch-sparse
RUN pip install --upgrade torch-cluster
RUN pip install --upgrade torch-spline-conv
RUN pip install torch-geometric

EXPOSE 8888

CMD ["bash",  "-c", "jupyter lab --ip 0.0.0.0 --no-browser --allow-root"]